/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizSacraRouteImport } from './routes/quiz-sacra'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizEncaminhamentoRouteImport } from './routes/quiz.encaminhamento'

const QuizSacraRoute = QuizSacraRouteImport.update({
  id: '/quiz-sacra',
  path: '/quiz-sacra',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizEncaminhamentoRoute = QuizEncaminhamentoRouteImport.update({
  id: '/quiz/encaminhamento',
  path: '/quiz/encaminhamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz-sacra': typeof QuizSacraRoute
  '/quiz/encaminhamento': typeof QuizEncaminhamentoRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz-sacra': typeof QuizSacraRoute
  '/quiz/encaminhamento': typeof QuizEncaminhamentoRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz-sacra': typeof QuizSacraRoute
  '/quiz/encaminhamento': typeof QuizEncaminhamentoRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz-sacra' | '/quiz/encaminhamento' | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz-sacra' | '/quiz/encaminhamento' | '/quiz'
  id: '__root__' | '/' | '/quiz-sacra' | '/quiz/encaminhamento' | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizSacraRoute: typeof QuizSacraRoute
  QuizEncaminhamentoRoute: typeof QuizEncaminhamentoRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz-sacra': {
      id: '/quiz-sacra'
      path: '/quiz-sacra'
      fullPath: '/quiz-sacra'
      preLoaderRoute: typeof QuizSacraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/encaminhamento': {
      id: '/quiz/encaminhamento'
      path: '/quiz/encaminhamento'
      fullPath: '/quiz/encaminhamento'
      preLoaderRoute: typeof QuizEncaminhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizSacraRoute: QuizSacraRoute,
  QuizEncaminhamentoRoute: QuizEncaminhamentoRoute,
  QuizIndexRoute: QuizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
